CREATE TABLE M2_EMPLOYEE
(
  EMP_ID NUMBER PRIMARY KEY,
  DEPT_ID NUMBER NOT NULL,
  FNAME VARCHAR2(50) NOT NULL,
  LNAME VARCHAR2(50) NOT NULL,
  POSITION VARCHAR2(50) NOT NULL,
  SALARY NUMBER(10) NOT NULL
);

CREATE TABLE M2_DEPARTMENT
(
  DEPT_ID NUMBER PRIMARY KEY,
  DEPT_NAME VARCHAR2(50) NOT NULL,
  LOCATION VARCHAR2(50) NOT NULL,
  NUM_EMP NUMBER NOT NULL
);

CREATE TABLE M2_CLIENTS
(
  CLIENT_ID NUMBER PRIMARY KEY,
  ACCT_ID NUMBER NOT NULL,
  FNAME VARCHAR2(50) NOT NULL,
  LNAME VARCHAR2(50) NOT NULL,
  TOTAL_BAL NUMBER(10) NOT NULL
);

CREATE TABLE M2_LOANS
(
  LOAN_ID NUMBER PRIMARY KEY,
  CLIENT_ID NUMBER NOT NULL,
  EMP_ID NUMBER NOT NULL,
  AMOUNT NUMBER(10) NOT NULL,
  DURATION VARCHAR2(10) NOT NULL
);
CREATE TABLE M2_ACCOUNTS
(
  ACCT_ID NUMBER PRIMARY KEY,
  CLIENT_ID NUMBER NOT NULL,
  ACCOUNT_NUM NUMBER NOT NULL,
  CURRENT_BAL NUMBER NOT NULL,
  
  CONSTRAINT UC_ACCOUNT_NUM UNIQUE (ACCOUNT_NUM)
);

CREATE TABLE M2_DEP_INS
(
  DEP_ID NUMBER PRIMARY KEY,
  EMP_ID NUMBER NOT NULL,
  COMP_ID NUMBER NOT NULL,
  FNAME VARCHAR2(50) NOT NULL,
  LNAME VARCHAR2(50) NOT NULL,
  RELATIONSHIP VARCHAR2(50)  
);

CREATE TABLE M2_INSURANCE
(
  COMP_ID NUMBER PRIMARY KEY,
  COMP_NAME VARCHAR2(100) NOT NULL,
  COVERAGE VARCHAR2(50) NOT NULL,
  LOCATION VARCHAR2(100) NOT NULL
);

CREATE TABLE M2_TRANSACTION
(
  TRANS_ID NUMBER PRIMARY KEY,
  CLIENT_ID NUMBER NOT NULL,
  ACCT_ID NUMBER NOT NULL,
  TRANS_DATE DATE NOT NULL,
  AMOUNT NUMBER(10) NOT NULL
);

CREATE TABLE M2_CHECK_DEPOSITS
(
  CHECK_ID NUMBER PRIMARY KEY,
  CLIENT_ID NUMBER NOT NULL,
  CHK_NUM NUMBER NOT NULL,
  BANK_SOURCE VARCHAR2(50) NOT NULL,
  DATE_RECEIVED DATE NOT NULL,
  DATE_PROCESSED DATE NOT NULL
);

ALTER TABLE M2_EMPLOYEE
ADD CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES M2_DEPARTMENT (DEPT_ID);